import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import { Layout } from "antd";
import { Button, Col, Container, Row } from 'react-bootstrap';
import { CardFeature, CardFeedback } from '@/components/ui';
import Masonry from 'react-masonry-css';
import Link from 'next/link';
import { faBook, faCheck, faClockRotateLeft, faGaugeSimple, faGraduationCap, faPen } from '@fortawesome/free-solid-svg-icons';


export default function Home() {
  const feedbacks = [
    {
      id: 1,
      name: "Huynh Ngoc Son",
      username: "huynhson89",
      time: "Sep 4, 2019",
      feedback: `<p>Thanks to Toeic Fighter, my TOEIC score increased from 500 to 900 in just 2 months of practice. <br>
Thank you Toeic Fighter team for creating a professional mock test environment like a real exam <br>
for me to achieve my goals.</p>`

    },
    {
      id: 2,
      name: "Huynh Ngoc Lam",
      username: "huynhson89",
      time: "Sep 4, 2019",
      feedback: `<p>Thanks to Toeic Fighter, my TOEIC score increased from 500 to 900 in just 2 months of practice. <br>
Thank you Toeic Fighter team for creating a professional mock test environment like a real exam <br>
for me to achieve my goals.</p>`

    },
    {
      id: 3,
      name: "Huynh Huy Hoang",
      username: "huyhoang34",
      time: "Sep 4, 2034",
      feedback: `<p>Thanks to Toeic Fighter, my TOEIC score increased from 500 to 900 in just 2 months of practice. <br>
Thank you Toeic Fighter team for creating a professional mock test environment like a real exam <br>
for me to achieve my goals.</p>`

    },
    {
      id: 4,
      name: "Huynh Ngoc Son",
      username: "huynhson89",
      time: "Sep 4, 2019",
      feedback: `<p>Thanks to Toeic Fighter, my TOEIC score increased from 500 to 900 in just 2 months of practice. <br>
Thank you Toeic Fighter team for creating a professional mock test environment like a real exam <br>
for me to achieve my goals.</p>`

    },
    {
      id: 5,
      name: "Huynh Ngoc Lam",
      username: "huynhson89",
      time: "Sep 4, 2019",
      feedback: `<p>Thanks to Toeic Fighter, my TOEIC score increased from 500 to 900 in just 2 months of practice. <br>
Thank you Toeic Fighter team for creating a professional mock test environment like a real exam <br>
for me to achieve my goals.</p>`

    },
    {
      id: 6,
      name: "Huynh Huy Hoang",
      username: "huyhoang34",
      time: "Sep 4, 2034",
      feedback: `<p>Thanks to Toeic Fighter, my TOEIC score increased from 500 to 900 in just 2 months of practice. <br>
Thank you Toeic Fighter team for creating a professional mock test environment like a real exam <br>
for me to achieve my goals.</p>`

    },
  ]

  return (
    <>
      <Head>
        <title>Toeic Fighter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <section className={styles.heroArea} style={{ backgroundImage: `url("https://preview.colorlib.com/theme/clever/img/bg-img/bg1.jpg.webp")` }}>
          <Container>
            <Row>
              <Col sm={12}>
                <div className={styles.heroContent}>
                  <h2>
                    Let&apos;s Study Together
                  </h2>
                  <Link href="/login">Get Started</Link>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={styles.expWrapper}>
          <Container fluid="md">
            <Row>
              <Col sm={12}>
                <div className={styles.exp}>
                  <h2 >Outstanding features of the site</h2>
                  <p>Here are the salient features of the website</p>
                </div>
              </Col>
            </Row>
            <Row>
              <Col sm={4} style={{ marginBottom: "20px" }}>
                <CardFeature icon={faBook} title="Test bank" des="Copious practice tests and mock 
                tests assist you in flexibly mastering the test with diverse topics and in different 
                areas" />
              </Col>
              <Col sm={4} style={{ marginBottom: "20px" }}>
                <CardFeature icon={faGraduationCap} title="Actual exam simulation"
                  des="The same format of practice test as the actual test will be such an advantage 
                for you to ace the exam successfully."/>
              </Col>
              <Col sm={4} style={{ marginBottom: "20px" }}>
                <CardFeature icon={faCheck} title="Detailed Result Statistics"
                  des="Once finishing each practice test, you will be provided with detailed result statistics 
                that show your learning progress."/>
              </Col>
              <Col sm={4} style={{ marginBottom: "20px" }}>
                <CardFeature icon={faPen} title="Easy-to-see interface"
                  des="The website provides a clear and scientific interface to help students do the test easily and quickly." />
              </Col>
              <Col sm={4} style={{ marginBottom: "20px" }}>
                <CardFeature icon={faGaugeSimple} title="Fast processing speed"
                  des="Fast processing speed makes it easy for students to take the test" />
              </Col>
              <Col sm={4} style={{ marginBottom: "20px" }}>
                <CardFeature icon={faClockRotateLeft} title="Save work history"
                  des="Record your work history to make it easy for students to see their progress" />
              </Col>
            </Row>
          </Container>
        </section>

        <section className={styles.feedback}>
          <div className={styles.fbWrapper}>
            <div className={styles.fbInner}>
              <h2>Happy Customers Are Our True Wealth</h2>
              <div className={styles.fbContent}>
                <Masonry
                  breakpointCols={{
                    default: 4,
                    1100: 3,
                    700: 2,
                    500: 1
                  }}
                  className="my-masonry-grid"
                  columnClassName="my-masonry-grid_column">
                  {
                    feedbacks && feedbacks.length > 0 && feedbacks.map((item: any) => {
                      return (
                        <CardFeedback key={item.id} name={item.name} username={item.username} feedback={item.feedback} />
                      )
                    })
                  }
                </Masonry>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
Home.Layout = Layout;
